In [53]:
#2.1入门知识

In [52]:
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x1=torch.arange(1,6,0.5)
x1

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [8]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
x.reshape(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
x.reshape(-1,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [14]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.randn(2,3)

tensor([[-2.1879, -0.6610,  1.3135],
        [-0.1182, -1.1677,  1.4615]])

In [17]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([2,3,4,5])

In [20]:
x+y

tensor([3, 5, 7, 9])

In [21]:
x**y

tensor([   1,    8,   81, 1024])

In [22]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[2,1,2,3],[2,4,5,5],[1,2,3,4]])

In [23]:
torch.cat((X,Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  2.,  3.],
        [ 2.,  4.,  5.,  5.],
        [ 1.,  2.,  3.,  4.]])

In [24]:
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  2.,  4.,  5.,  5.],
        [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]])

In [25]:
X==Y

tensor([[False,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X.sum()

tensor(66.)

In [27]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [28]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [30]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [34]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X.shape

torch.Size([3, 4])

In [36]:
X[0:2,:]=12

In [37]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [38]:
before=id(Y)
Y=Y+X
id(Y),before

(2665019625368, 2665019620872)

In [39]:
Z=torch.zeros_like(Y)
print(id(Z))
Z[:]=X+Y
print(id(Z))

2665019659272
2665019659272


In [40]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [41]:
a=torch.tensor([3.5])

In [42]:
type(a)

torch.Tensor

In [43]:
b=a.item()

In [44]:
type(b)

float

In [45]:
int(a)

3

In [46]:
type(int(a))

int

In [47]:
type(a)

torch.Tensor

In [48]:
#2.2数据预处理

In [55]:
import os
os.makedirs(os.path.join("..","data"),exist_ok=True)
data_file=os.path.join("..","data","house_tiny.csv")
with open(data_file,"w") as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [56]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [57]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [58]:
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [59]:
import torch
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [60]:
#2.3-线性代数
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [61]:
A[0,0]=1

In [62]:
A,B

(tensor([[ 1.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))